#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TequiScanner.Droid.Resource", IsApplication=true)]

namespace TequiScanner.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int checkMarkTintColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int failureMarkTintColor = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int mainColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int secondaryColor = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int textColor = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int background = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int main_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int secondary_color = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_checked_mark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_failure_mark = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int apiErrorMessage = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int browsePhotoBtn = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int loadingView = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int takePhotoBtn = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textZone = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ScannerResult = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int api_error_message = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int browse_photo = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int take_photo = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnimatedCircleLoadingView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int AnimatedCircleLoadingView_checkMarkTintColor = 2;
			
			// aapt resource value: 3
			public const int AnimatedCircleLoadingView_failureMarkTintColor = 3;
			
			// aapt resource value: 0
			public const int AnimatedCircleLoadingView_mainColor = 0;
			
			// aapt resource value: 1
			public const int AnimatedCircleLoadingView_secondaryColor = 1;
			
			// aapt resource value: 4
			public const int AnimatedCircleLoadingView_textColor = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
